---
# in _config.yml
title: "Introduction to Computing 101"
author: "Adam Zvolanek"
toc: true
post_search: true
edit_page_button: true
timezone: "America/Chicago"
repository:
  url: "https://github.com/adamzvolanek/silver-barnacle/"
launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com"
execute:
  execute_notebooks: "off"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-toc
exclude:
  - LICENSE
  - README.md
  - make.sh
