# in _config.yml
title: "Introduction to Computing"
execute:
  execute_notebooks: "off"
author: "<Insert Author>"
repository:
  url: "https://github.com/PredictiveScienceLab/data-analytics-se"
  path_to_book: "lecturebook"
launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com"
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year