---
# in _config.yml
title: "Introduction to Computing 101"
execute:
  execute_notebooks: "off"
author: "Adam Zvolanek"
repository:
  url: "https://github.com/adamzvolanek/silver-barnacle/"
  path_to_book: "lecturebook"
launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com"
sphinx:
  config:
    bibtex_reference_style: author_year
    bibtex_bibfiles: "references.bib"